### ISSUE TITLE
Doubly Robust

### ISSUE THREAD

**Issue by pedrohcgs** [TsaiLintung/fastdid#1]
This is really great!!!

I was wondering if there is a doubly robust implementation, too.

Also, I would love to include some of these advances into the 'did' package, eventually.

Thanks a lot!

**Comment by TsaiLintung** [comment]
@pedrohcgs Thank you so much for reaching out and for the kind words!

DR is not currently available, but it is straightforward to implement and will be added. I hope to get it done in a few weeks.

It would be fantastic if these changes could contribute to making 'did' faster. The improvements in fastdid should generally be compatible but some might introduce additional data requirements. I'd also love to discuss these further. Thanks.

**Comment by pedrohcgs** [comment]
I would love to discuss this!!!
Please send me an email!

**Comment by TsaiLintung** [comment]
I'm happy to report that fastdid now supports DR as well as OR after 0.9.2. I will close this issue now. Thanks.
