### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by grantmcdermott** [TsaiLintung/fastdid#2]
I've been playing around with this package a bit today and looks very impressive. Nice work!

I have some quick suggestions based on my early experiences:

- Set an internal catch for `inherits(dt, 'data.table')` at the top of the `fastdid` script and then coerce to data.table if FALSE. This will save some user headaches, since the standard input object that everyone expects is a regular data.frame.
- Speaking of `dt`, I'd personally recommend using `data` as the input object argument since this is the standard argument name.
- I strongly recommend setting `copy = TRUE` as the default. Reference semantics can be tricky and users are likely going to be be frustrated when they try to re-run the same model---but with different result_type---only to be confronted by unexpected errors... Or find that their data frame has be altered in ways that makes other operations behave differently.
- Can you you add confidence intervals to the return object in addition to SEs? This will be easier on the internal side than for the user, since you have better insight into the right DoF correction, etc.

Thanks again. Cheers.

**Comment by TsaiLintung** [comment]
These are great suggestions, I will incorporate them in the next patch. Thank you so much for the feedback.

**Comment by TsaiLintung** [comment]
I'm happy to report that your suggestions have been incorporated into the 0.9.2 update. The exception is CI, I decided to defer it until implementing simultaneous CI (for now the CI would just be att + 1.96 se anyway). Thanks again for the feedback. I will close this issue now.

**Comment by grantmcdermott** [comment]
🎉
